service: pkg-two

package:
  individually: true

provider:
  name: aws
  runtime: nodejs18.x
  timeout: 30
  region: us-east-1

functions:
  simpleExampleOne:
    handler: index.handler
    name: simple-example-one
