service: pkg-one

package:
  individually: true

provider:
  name: aws
  runtime: nodejs18.x
  timeout: 30
  region: us-east-1

functions:
  simpleExampleTwo:
    handler: index.handler
    name: simple-example-two
